
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  COMPANY_NAME: Avanade Deutschland GmbH

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Show Environment Variables
      run: echo "repository variable : $REPOSITORY_VAR"
      env:
        REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
