name: BlazorAdventureWorks
run-name: BlazorAdventureWorks_CI

on: push

jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4.1.1
    - name: Restore Resources
      run: dotnet restore
  Build:
    runs-on: ubuntu-latest
    needs: Integration
    steps:
      - name: Build
        run: dotnet build
