name: BlazorAdventureWorks
run-name: BlazorAdventureWorks_CI

on: [push, pull_request]

permissions: read-all

env:
  AUTHOR: Neyamat Ullah

defaults:
  run:
    shell: bash
    working-directory: ./Scripts

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  

jobs:
  Prepare-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build
  Test-Code:
    needs: Prepare-Code
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Test
        run: dotnet test
  Documentation:
    needs: Test-Code
    runs-on: ubuntu-latest
    steps:
      - name: Author
        run: echo "Authored by $AUTHOR"
          
        
