name: BlazorAdventureWorks
run-name: BlazorAdventureWorks_CI

on: [push, pull_request]

jobs:
  Code-Preparation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
