name: BlazorAdventureWorks
run-name: BlazorAdventureWorks_CI

on: [push, pull_request]

env:
  AUTHOR: Neyamat Ullah

jobs:
  Prepare-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build
  Test-Code:
    needs: Prepare-Code
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Test
        run: dotnet test
  Documentation:
    needs: Prepare-Code
    runs-on: ubuntu-latest
    steps:
      - name: Author
        run: echo "Authored by: $env.AUTHOR"
          
        
