name: BlazorAdventureWorks_CI
run-name: BlazorAdventureWorks

on: push

env:
  AUTHOR: Neyamat Ullah

jobs:
  First_Job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "$AUTHOR"
