name: BlazorAdventureWorks
run-name: BlazorAdventureWorks_CI

on: push

jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Restore solution
        run: dotnet restore
  Build:
    runs-on: ubuntu-latest
    needs: Integration
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Build solution
        run: dotnet build
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Test solution
        run: dotnet test
